#IMPORTANT TO USE THIS PAD WITH SUMMITXL
#CHECK THE IF THE SWITCH IS IN DIRECT INPUT (D)
#AND THE MODE LED IS OFF

pad_type: logitechf710
num_of_buttons: 11

#MOVEMENT
axis_linear_x: 1
axis_linear_y: 0
axis_angular: 3
#FOR SUMMITX
axis_linear_z: 5
scale_linear_z: 20.0
#SCALE FACTOR
scale_linear: 3.0
scale_angular: 3.0

#RB1 CONTROLS
button_speed_up: 3
button_speed_down: 0
button_dead_man: 5
button_output_1: 2
button_output_2: 1
output_1: 10
output_2: 11

button_kinematic_mode: 7
cmd_service_home:  /robot_controller/home
check_message_timeout: false
